### ISSUE TITLE
Fails to build with spdlog 0.16.2

### ISSUE THREAD

**Issue by ryandesign** [google/aff4#51]
aff4 fails to build with spdlog 0.16.2:

```
data_store.cc:92:50: error: too many arguments to function call, expected single argument 'logger_name', have 2 arguments
    : logger(spdlog::stderr_logger_mt("console", true)),
             ~~~~~~~~~~~~~~~~~~~~~~~~            ^~~~
```

The second argument of `stderr_logger_mt` was removed in October 2016 in https://github.com/gabime/spdlog/commit/0cfdad4d0b6dde761debe408fc7c9501e697b914.

**Comment by scudette** [comment]
Sorry - I initially developed with the spdlog which comes on Ubuntu which ended up being too old, so I changed to the latest in the latest commit. Did you pull git head?  I also added instructions for statically building for linux and windows, and those suggest to git pull spdlog to get the latest version.

**Comment by ryandesign** [comment]
Sorry, I had assumed the latest commit wasn't relevant to me, since its title was "Windows bug fixes" and I'm not on Windows.

Git head has too many build errors to paste here; here's a gist: https://gist.github.com/ryandesign/e771b85f44152ac66d0cdf4cbb490220

**Comment by scudette** [comment]
Ah I see. Your logs show breakage in the tests directory which I have not gotten around to fixing yet :-). Building in the src directory should work and produce a working imager binary.
